/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalleresRouteImport } from './routes/talleres'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as MaquinasRouteImport } from './routes/maquinas'
import { Route as MantenimientosRouteImport } from './routes/mantenimientos'
import { Route as FichasTecnicasRouteImport } from './routes/fichas-tecnicas'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaquinasIdRouteImport } from './routes/maquinas.$id'

const TalleresRoute = TalleresRouteImport.update({
  id: '/talleres',
  path: '/talleres',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const MaquinasRoute = MaquinasRouteImport.update({
  id: '/maquinas',
  path: '/maquinas',
  getParentRoute: () => rootRouteImport,
} as any)
const MantenimientosRoute = MantenimientosRouteImport.update({
  id: '/mantenimientos',
  path: '/mantenimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const FichasTecnicasRoute = FichasTecnicasRouteImport.update({
  id: '/fichas-tecnicas',
  path: '/fichas-tecnicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaquinasIdRoute = MaquinasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MaquinasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/fichas-tecnicas': typeof FichasTecnicasRoute
  '/mantenimientos': typeof MantenimientosRoute
  '/maquinas': typeof MaquinasRouteWithChildren
  '/reportes': typeof ReportesRoute
  '/talleres': typeof TalleresRoute
  '/maquinas/$id': typeof MaquinasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/fichas-tecnicas': typeof FichasTecnicasRoute
  '/mantenimientos': typeof MantenimientosRoute
  '/maquinas': typeof MaquinasRouteWithChildren
  '/reportes': typeof ReportesRoute
  '/talleres': typeof TalleresRoute
  '/maquinas/$id': typeof MaquinasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/fichas-tecnicas': typeof FichasTecnicasRoute
  '/mantenimientos': typeof MantenimientosRoute
  '/maquinas': typeof MaquinasRouteWithChildren
  '/reportes': typeof ReportesRoute
  '/talleres': typeof TalleresRoute
  '/maquinas/$id': typeof MaquinasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracion'
    | '/fichas-tecnicas'
    | '/mantenimientos'
    | '/maquinas'
    | '/reportes'
    | '/talleres'
    | '/maquinas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracion'
    | '/fichas-tecnicas'
    | '/mantenimientos'
    | '/maquinas'
    | '/reportes'
    | '/talleres'
    | '/maquinas/$id'
  id:
    | '__root__'
    | '/'
    | '/configuracion'
    | '/fichas-tecnicas'
    | '/mantenimientos'
    | '/maquinas'
    | '/reportes'
    | '/talleres'
    | '/maquinas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  FichasTecnicasRoute: typeof FichasTecnicasRoute
  MantenimientosRoute: typeof MantenimientosRoute
  MaquinasRoute: typeof MaquinasRouteWithChildren
  ReportesRoute: typeof ReportesRoute
  TalleresRoute: typeof TalleresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talleres': {
      id: '/talleres'
      path: '/talleres'
      fullPath: '/talleres'
      preLoaderRoute: typeof TalleresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maquinas': {
      id: '/maquinas'
      path: '/maquinas'
      fullPath: '/maquinas'
      preLoaderRoute: typeof MaquinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mantenimientos': {
      id: '/mantenimientos'
      path: '/mantenimientos'
      fullPath: '/mantenimientos'
      preLoaderRoute: typeof MantenimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fichas-tecnicas': {
      id: '/fichas-tecnicas'
      path: '/fichas-tecnicas'
      fullPath: '/fichas-tecnicas'
      preLoaderRoute: typeof FichasTecnicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maquinas/$id': {
      id: '/maquinas/$id'
      path: '/$id'
      fullPath: '/maquinas/$id'
      preLoaderRoute: typeof MaquinasIdRouteImport
      parentRoute: typeof MaquinasRoute
    }
  }
}

interface MaquinasRouteChildren {
  MaquinasIdRoute: typeof MaquinasIdRoute
}

const MaquinasRouteChildren: MaquinasRouteChildren = {
  MaquinasIdRoute: MaquinasIdRoute,
}

const MaquinasRouteWithChildren = MaquinasRoute._addFileChildren(
  MaquinasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  FichasTecnicasRoute: FichasTecnicasRoute,
  MantenimientosRoute: MantenimientosRoute,
  MaquinasRoute: MaquinasRouteWithChildren,
  ReportesRoute: ReportesRoute,
  TalleresRoute: TalleresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
